obstacle_range: 2.5        
raytrace_range: 3.5

robot_radius: 0.20
footprint_padding: 0.01    
map_type: costmap

transform_tolerance: 0.5

observation_sources: scan

scan:
  sensor_frame: camera_imu_optical_frame
  data_type: scan
  topic: /scan
  marking: true
  clearing: true
  min_obstacle_height: 0.1
  max_obstacle_height: 2.0

inflation_radius: 0.4        
cost_scaling_factor: 3.0

obstacle_layer:
  enabled: true
  max_obstacle_height: 2.0
  obstacle_range: 2.5
  raytrace_range: 3.0

inflation_layer:
  enabled: true

static_layer:
  enabled: true

